export default function CV() {
  return (
    <div>
      <title>Isabelle Khan portfolio</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />

      <main className=" bg-gradient-to-bl from-green-900/30 to-white-500 px-10 md:px-20 lg:px-40"></main>
    </div>
  );
}
